chore: run go fmt (#1983)
Run,

```
bazel run @go_sdk//:bin/go -- fmt $(go list ./... | grep -v /bazel-/
```

The one file changed is tripping CI in the aspect-cli repo where go fmt
is
checked.https://github.com/aspect-build/aspect-cli/actions/runs/4737382483/jobs/8410121279?pr=425

```
$ ./.github/workflows/tidy_up_repository.sh
...
@@ -269,8 +269,8 @@ var testCases = []struct {
 		ts: `
 			import type { Foo } from "my/types";
 		`,
-		filename:  "typeImport-unused.ts",
-		expected:  []string{"my/types"},
+		filename: "typeImport-unused.ts",
+		expected: []string{"my/types"},
 		typeOnly: true,
 	},
 }
Error: ERROR: Please run 'bazel run @go_sdk//:bin/go -- fmt $(go list ./... | grep -v /bazel-/)' and commit the changes.
Error: Process completed with exit code 1.
```

**Type of change**

- [x] Chore (any other change that doesn't affect source or test files)

**Test plan**

How has this been tested?

- [x] Covered by existing test cases